version: '3'

services:

  mygogs:
    image: gogs/gogs
    volumes:
      - ./gogs-data:/data
    networks:
      bw-services:
        aliases:
          - mygogs
    labels:
      - bunkerweb.SERVER_NAME=www.example.com
      - bunkerweb.USE_REVERSE_PROXY=yes
      - bunkerweb.REVERSE_PROXY_HOST=http://mygogs:3000
      - bunkerweb.REVERSE_PROXY_HEADERS_1=Authorization $http_authorization
      - bunkerweb.MAX_CLIENT_SIZE=1G

networks:
  bw-services:
    external:
      name: bw-services