version: "3"

services:
  mymoodle:
    image: bitnami/moodle:4.1.0
    networks:
      - bw-services
    depends_on:
      - mydb
    volumes:
      - moodle_files:/bitnami/moodle
      - moodle_data:/bitnami/moodledata
    environment:
      - MOODLE_USERNAME=admin # replace with your moodle admin username
      - MOODLE_PASSWORD=password # replace with your moodle admin password
      - MOODLE_EMAIL=moodle@example.com # replace with your moodle admin email
      - MOODLE_SITE_NAME=My Moodle # replace with your moodle site name
      - MOODLE_DATABASE_HOST=mydb
      - MOODLE_DATABASE_NAME=moodle
      - MOODLE_DATABASE_USER=user
      - MOODLE_DATABASE_PASSWORD=db-user-pwd # replace with a stronger password (must match MYSQL_PASSWORD)
    deploy:
      placement:
        constraints:
          - "node.role==worker"
      labels:
        - bunkerweb.SERVER_NAME=www.example.com
        - bunkerweb.USE_REVERSE_PROXY=yes
        - bunkerweb.REVERSE_PROXY_URL=/
        - bunkerweb.REVERSE_PROXY_HOST=https://mymoodle:8443

  # For the database, you can refer to the swarm integration example including a database
  # In this example, you will need to add the following lines to the mydb service:
  # - MARIADB_CHARACTER_SET=utf8mb4
  # - MARIADB_COLLATE=utf8mb4_unicode_ci

networks:
  bw-services:
    external:
      name: bw-services

volumes:
  db_data:
  moodle_files:
  moodle_data:
