version: "3.3"

services:
  mydrupal:
    image: drupal:9.4-apache
    networks:
      - bw-services
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-themes:/var/www/html/themes
      - drupal-sites:/var/www/html/sites
    deploy:
      placement:
        constraints:
          - "node.role==worker"
      labels:
        - bunkerweb.SERVER_NAME=www.example.com # replace with your domain
        - bunkerweb.AUTO_LETS_ENCRYPT=yes
        - bunkerweb.USE_REVERSE_PROXY=yes
        - bunkerweb.REVERSE_PROXY_URL=/
        - bunkerweb.REVERSE_PROXY_HOST=http://mydrupal
        - bunkerweb.LIMIT_REQ_URL_1=/core/install.php
        - bunkerweb.LIMIT_REQ_RATE_1=5r/s

  # For the database, you can refer to the swarm example including a database

networks:
  bw-services:
    external:
      name: bw-services

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-themes:
  drupal-sites:
  db-data:
