version: "3"

services:
  myredmine:
    image: redmine:5.0.4-alpine
    restart: always
    volumes:
      - ./redmine-data:/usr/src/redmine/files
    networks:
      bw-services:
        aliases:
          - myredmine
    environment:
      - REDMINE_DB_MYSQL=mydb
      - REDMINE_DB_DATABASE=redminedb
      - REDMINE_DB_USERNAME=user
      - REDMINE_DB_PASSWORD=db-user-pwd # replace with a stronger password (must match MYSQL_PASSWORD)
    labels:
      - bunkerweb.SERVER_NAME=www.example.com
      - bunkerweb.USE_REVERSE_PROXY=yes
      - bunkerweb.REVERSE_PROXY_URL=/
      - bunkerweb.REVERSE_PROXY_HOST=http://myredmine:3000

  # For the database, you can refer to the autoconf example including a database

networks:
  bw-services:
    external:
      name: bw-services
