version: '3.8'

services:

  redis:
    image: redis:alpine
    networks:
      - net_config
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role==worker"

networks:
  net_config:
    external: true
