version: "3"

services:
  myjoomla:
    image: joomla:4-apache
    networks:
      bw-services:
        aliases:
          - myjoomla
    volumes:
      - ./joomla-files:/var/www/html
    environment:
      - JOOMLA_DB_HOST=mydb
      - JOOMLA_DB_NAME=joomla_db
      - JOOMLA_DB_USER=user
      - JOOMLA_DB_PASSWORD=db-user-pwd # replace with a stronger password (must match MYSQL_PASSWORD)
    labels:
      - bunkerweb.SERVER_NAME=www.example.com
      - bunkerweb.USE_REVERSE_PROXY=yes
      - bunkerweb.REVERSE_PROXY_URL=/
      - bunkerweb.REVERSE_PROXY_HOST=http://myjoomla
      - bunkerweb.LIMIT_REQ_URL_1=/administrator/
      - bunkerweb.LIMIT_REQ_RATE_1=8r/s
      - bunkerweb.LIMIT_REQ_URL_2=/installation/index.php
      - bunkerweb.LIMIT_REQ_RATE_2=8r/s

  # For the database, you can refer to the example of the autoconf including a database

networks:
  bw-services:
    external:
      name: bw-services
