name: Build, push and deploy (AVISTO-PROD)

on:
  push:
    branches: [feature/github-actions]

jobs:

  # Push to Avisto Harbor Docker registry
  push-docker-harbor:
    runs-on: ubuntu-latest
    steps:
      # Prepare
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Set variables
        run: |
          VER=$(cat VERSION | tr -d '\n')
          echo "VERSION=$VER" >> $GITHUB_ENV
      - name: Setup Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Login to private repository
        uses: docker/login-action@v2
        with:
          registry: rgy.k8s.devops-svc-ag.com/avisto
          username: robot$avisto+avisto
          password: ${{ secrets.PRIVATE_REGISTRY_TOKEN }}
      # Build and push
      - name: Build and push BW
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: rgy.k8s.devops-svc-ag.com/avisto/bunkerweb:${{ env.VERSION }}
